[package]
name = "tun0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
etherparse = { version = "0.15.0", features = ["std"] }
pnet = "0.35.0"
rand = "0.8.5"
tun-tap = "0.1.4"
