// XDP eBPF program

#include <linux/bpf.h>
#include <stdbool.h>

#include <bpf/bpf_helpers.h>

// Represent perf event data
struct perf_trace_event {
  __u64 timestamp;
  __u32 processing_time_ns;
  __u8 type;
};

#define TYPE_ENTER 1
#define TYPE_DROP 2
#define TYPE_PASS 3

// output_map - used to store the perf events generated by XDP program
struct {
  // Map to store perf event
  __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
  __uint(key_size, sizeof(int));
  __uint(value_size, sizeof(struct perf_trace_event));
  __uint(max_entries, 1024);
} output_map SEC(".maps");

// XDP Program function
// xdp_lib - serves as XDP eBPF program entry point, and called for every
// incoming packet
SEC("xdp")
int xdp_lib(struct xdp_md *ctx) {
  // Handling perf events and collecting data

  struct perf_trace_event e = {};

  // Perf event for entering xdp program
  e.timestamp = bpf_ktime_get_ns();
  e.type = TYPE_ENTER;
  e.processing_time_ns = 0;
  bpf_perf_event_output(ctx, &output_map, BPF_F_CURRENT_CPU, &e, sizeof(e));

  // Packet processing logic
  // For now, this drop drops 50% of the packets
  if (bpf_get_prandom_u32() % 2 == 0) {
    // Perf event for dropping packets
    e.type = TYPE_DROP;
    __u64 ts = bpf_ktime_get_ns();
    e.processing_time_ns = ts - e.timestamp;
    e.timestamp = ts;
    bpf_perf_event_output(ctx, &output_map, BPF_F_CURRENT_CPU, &e, sizeof(e));
    return XDP_DROP;
  }

  // Perf event for passing packet
  e.type = TYPE_PASS;
  __u64 ts = bpf_ktime_get_ns();
  e.processing_time_ns = ts - e.timestamp;
  e.timestamp = ts;
  bpf_perf_event_output(ctx, &output_map, BPF_F_CURRENT_CPU, &e, sizeof(e));

  return XDP_PASS;
}
